### ISSUE TITLE
Translate App in French

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#17]
Using Qt linguistic it would be easy.

**Comment by dridk** [comment]
@Oodnadatta it would be a good training for you, if you want to translate Regovar in French. 
I will teach you how if you are interesting to take this issues.

**Comment by dridk** [comment]
@JuneBS Try to compile and run fastQt from your computer after installed Qt-sdk. 
Then I will teach you how to translate. it's really easy. Let me know !

**Comment by Jnsll** [comment]
I've got some issue. When i do 'qmake', i've got that error "Project ERROR: Unknown module(s) in QT: charts". ... 
PS: I have been on the Qt linguist page. Does not seem too difficult.

Edit: Natir helped me to resolve the issue. (qt5-charts installed now).

**Comment by dridk** [comment]
Be sure you have Qt > 5.7 . ( qmake --version)
During installation, you must check "QtChart" module . If you already installled QtSdk, you can update your installation by running $YOUR_QT_INSTALL_PATH/MaintenanceTool

**Comment by Jnsll** [comment]
On with branch can we work for the translation?

**Comment by natir** [comment]
Create branch from devel.

**Comment by dridk** [comment]
@JuneBS You should have a file : fastqc_fr.ts generated when when you compile Fastqt. This file can be open with Qtlinguist

**Comment by Jnsll** [comment]
No file named fastqc_fr.ts is generated when compiling. But i used `lupdate FastQt.pro` and it did the job.

**Comment by dridk** [comment]
@JuneBS you can change this line from your branch to test your translation https://github.com/labsquare/fastQt/blob/translation_fr/main.cpp#L46
Be sure you have translation_fr.qm after doing lupdate translation_fr.ts

Thanks

**Comment by dridk** [comment]
![image](https://cloud.githubusercontent.com/assets/1911063/23487238/080125a0-fee5-11e6-87d1-a24d71c3ea4f.png)
