### ISSUE TITLE
Export Graph as picture

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#19]
Exporting graph each graph as png . 
Exporting all analyse as pdf

**Comment by natir** [comment]
It's possible to export image as svg ?

I think export all analyse in one pdf isn't a good idea create a directory with each graph in one file is more adaptable.

**Comment by dridk** [comment]
it may be possible to render svg. Not sure .. 
I will try with QSvgRenderer

**Comment by natir** [comment]
I try to use a adaptation of this [code](https://stackoverflow.com/questions/22356296/render-existing-qt-widget-into-svg), but QChartView didn't want render in QSvgGenerator.

Pixmap image we can use view->grab.save("image.png")

**Comment by dridk** [comment]
let me try

**Comment by natir** [comment]
I find a solution it's ok

**Comment by natir** [comment]
04efec55bee1a3d0ae331a32945a886bfcadc205 add a possibility to all analyse to get result widget in Pixmap or in SVG.

For GUI application we can do : 
- export current graph (default name : filename_graph_name.format)
- export all graph of file (default name: filename/graph_name.format)
- export all graph of all file (default name : fastqt/filename/graph_name.format)

**Comment by dridk** [comment]
I changed my mind, sorry for that. 
But we must have Analysis::save(const QString& filename) as you said before. Check the extension ( QFileInfo) and do the save in function.

**Comment by dridk** [comment]
What about table ? I can't export table as a picture. I need to export them as a file . 
So, each analysis should have a export_data(const QString& filename). 
From them, you can export image, or csv file etc .... 

FastQC export all data as html page ... Is it a good idea ? 
Also, from the gui I don't know what action is necessary.. export all results ? Export result from analysis ? 
And what about svg / png export ... 
So, we need to clarify everything .

**Comment by dridk** [comment]
can be improve in next milestone.
