### ISSUE TITLE
Clean QUazip reference

### ISSUE THREAD

**Issue by natir** [labsquare/fastQt#29]
In some comment we can see reference to QUazip but we replace this by KArchive.

I little clean up and check if commented code do important think is require.

**Comment by natir** [comment]
Ok the reference of QuaZip can be found in : 

- [analysisrunner](https://github.com/labsquare/fastQt/blob/devel/analysis/analysisrunner.cpp#L103)
- quazip class [implementation](https://github.com/labsquare/fastQt/blob/devel/utils/quagzipfile.cpp) [declaration](https://github.com/labsquare/fastQt/blob/devel/utils/quagzipfile.h)

quazip class is just dead code we can remove it.

Comment in analysisrunner say it's possible the FastqReader::percentComplet function can return 0. But in [implementation](https://github.com/labsquare/fastQt/blob/master/sequence/abstractsequencereader.cpp#L34) we see this function return 0 just when file is empty.
Maybe we can check if file is empty early and remove this comment.

@dridk did you have opinion about this point ?

**Comment by dridk** [comment]
you can remove everything. 
At the end, the method to compute percent will probably change. 
Actually the problem is I don't know the totalSize of a compress file. I have to read the whole file one time before starting analysis. 
@Arkanosis suggest me to get a percent progression directly from compressed bloc . .But I don't know how.

**Comment by Arkanosis** [comment]
I'll rewrite this to avoid decompressing files twice (I'm pretty sure more time is spent currently decompressing compared to actually computing the statistics). Feel free to clean up, though, as I'm not sure when I'll do this.

**Comment by dridk** [comment]
Not relevant to this issue. See #38
