### ISSUE TITLE
Add drop fastq file 

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#33]
Enable drop file from desktop to fastqt

**Comment by natir** [comment]
I think the close hook didn't take the commit https://github.com/labsquare/fastQt/commit/61bf3e30bf3e497f0d264c832e5f5fee9aeca96d

**Comment by dridk** [comment]
yes.. seems it close only with master branch

**Comment by natir** [comment]
it's true https://help.github.com/articles/closing-issues-via-commit-messages/
