### ISSUE TITLE
Application Icon 

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#35]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42015876)](https://www.bountysource.com/issues/42015876-application-icon?utm_source=42015876&utm_medium=shield&utm_campaign=ISSUE_BADGE)

We need an icon for FastQt. A based template for all labsquare application would be awesome. 
@it-s If you do the job, please join idea, mokup here. 
@ikit you can do it too . 

Following some idea.. If you can mix both picture. 
![unnamed](https://cloud.githubusercontent.com/assets/1911063/22929646/017d2c9e-f2bd-11e6-9c15-9f823365b430.png)

Currently, I have a stupid ugly bird ...

**Comment by maxulysse** [comment]
Silly idea, as I was just passing by ;-)
![testlogo](https://cloud.githubusercontent.com/assets/1019628/22930947/f1d2cd8e-f2c2-11e6-92c4-c22dc5c7aa47.png)

And I just noticed it looks a lot like the MultiQC logo...

**Comment by dridk** [comment]
It's the a try ! All ideas are welcome!

**Comment by dridk** [comment]
[DnaStar](https://www.dnastar.com/t-products-dnastar-lasergene-molecular-biology.aspx) is a commercial company and can be a model for Labsquare. Having the same layout model for all labsquare application icon would be awesome. 
Check application icon from DNA Star to see what I mean :[ DNA STAR softwares list ](https://www.dnastar.com/t-products-dnastar-lasergene-molecular-biology.aspx)

**Comment by ajmos** [comment]
@dridk. So for lay-people, LabQT is a tool "which process DNA sequence file and generate several plot and statistics."

Can you give me a real-world example of when/where/how/for whom this would be used. I can always just play along with the theme you provided but I can probably make a better logo if I really understand what LabQT is all about

**Comment by dridk** [comment]
@ajmos Thanks you for your reply ! LabQt doesn't exist. It's Labquare community and FasQt application.

### Labsquare

Labsquare is a community of developers who want to develop opensource gui and native software for genomics. 
Genomic is a new science that is interested in data comming from DNA sequencing. Watch this short video to understand  ["what is genomics" ](https://www.youtube.com/watch?v=mmgIClg0Y1k). 
Actually many genomics tools are Free and opensource supported by a strong opensource philosophy.  But most of them are only intended for expert without Graphics user interface. Only commercial company are doing "nice" User interface. 
Labsquare team would like to fill the void by doing several genomics application for non expert user like biologist and medics. 
For now, we are doing Native and cross platform application using Qt/C++ technology.
Actualy the logo of Labsquare is the following one : 
 https://avatars3.githubusercontent.com/u/2106259?v=3&s=200
But you can update it as you want. The logo displays a square with two "L" character like "L" from Labsquare. 

### FastQt 

FastQt is the first application released by labsquare. This tools analyzes files ( *.fastq extension) comming from a DNA sequencer ( [video example ](https://www.youtube.com/watch?v=WYBzbxIfuKs)). The file contains many sequences of DNA with  qualities scores telling if sequences are good or bad. [See wikipedia](https://en.wikipedia.org/wiki/FASTQ_format) for more information. 
After getting Fastq files from a DNA sequencer, biologist must analyse them to verify the quality. FastQt is a C++/Qt clone of [FastQC](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/), a Java application. Both of them, takes Fastq files as input and produces several plots and statistics to describe dna sequences and qualities. The advantage of fastQt compared to FastQC is that it is faster powered by Qt/C++. And ofcourse it's nicer.
FastQt is a tool among other tools that we want to create. Having same theme styles for all applications would be awesome. ( Like Excel, Word, Power point keep same design) . Next applications that we are working on are listed bellow : 

### Application comming soon 

- **BigBrowser** : 
A native genom browser, to explore genom data. Look the [Ensembl genom browser](http://www.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32313779-32401961) for example. 
Actually, we have doing this : https://www.youtube.com/watch?v=Y7ouuS8Ooo0
Logo Idea : an eye with two curve of DNA for eye outline. 

- **CuteVariant** : 
A filter for genomics variation. For example If I sequence your DNA, I will get a file which contains all your DNA variation. CuteVariant filters variations and tells you if the variation do nothing or is responsible for a disease .... or a power (X-men ). You can try this really cute web application with a data set demo : [http://gene.iobio.io/](http://gene.iobio.io/) 
Logo idea: DNA nucleotid (A,C,G,T) which fall inside a filter. 

### In Brief 

We need an application logo for FastQt. Because this application has already been released as 0.1. 
This tool analyze DNA sequencing output with several plot . 
Keywords for logo are :  DNA, Sequencing, qualities,genomics, genetics, biology, analysis, plot, statistics,fastq,dna sequence 

### Commercial company example

- https://www.dnastar.com/t-products-dnastar-lasergene-molecular-biology.aspx
- http://goldenhelix.com/

**Comment by dridk** [comment]
@ajmos See genomics workflow  ! Each icons can be a software ( source: https://omictools.com/)
![567bd673695d2](https://cloud.githubusercontent.com/assets/1911063/23105809/7b008080-f6e5-11e6-9d01-ff84e9d67164.png)

FastQt is a quality control application

**Comment by dridk** [comment]
From Omics tools, Fastqc would have this category icons : 
![quality-control6-1](https://cloud.githubusercontent.com/assets/1911063/23105920/9c7dc186-f6e6-11e6-8784-1f49a3e29a0b.png)

CuteVariant this one : 
![gene-prioritization-2](https://cloud.githubusercontent.com/assets/1911063/23105929/a71f5974-f6e6-11e6-9962-c1080eb9eeba.png)


BigBrowser this one
![genome-visualization-1](https://cloud.githubusercontent.com/assets/1911063/23105931/ad417ae4-f6e6-11e6-80fe-5a47b8697502.png)

**Comment by ajmos** [comment]
Would you be open to something significantly more abstract?

**Comment by dridk** [comment]
I don't care actually... Everything is better than the actual bird icon ! 
But don't make it abstract too much, like a black rectangle :D

**Comment by dridk** [comment]
I have an idea ! Keep the same shape for all labsquare apps ! For example, the following smooth polygon shape designed by @it-s 
![khangman_mobile_icon_by_it_s-d4pf5le](https://cloud.githubusercontent.com/assets/1911063/23107545/3d333364-f6ff-11e6-8107-55938749bbdf.png)

**Comment by dridk** [comment]
or the following color styles background with simple motif on it . Made by @it-s
![gluon_invaders_by_it_s](https://cloud.githubusercontent.com/assets/1911063/23107574/a4da6e74-f6ff-11e6-8555-cc87787f5b05.png)
![gluon_player_icon_by_it_s](https://cloud.githubusercontent.com/assets/1911063/23107575/a59854ca-f6ff-11e6-995e-90b7ea225816.png)
![gluon_creator_icon_by_it_s](https://cloud.githubusercontent.com/assets/1911063/23107576/a6a17c0c-f6ff-11e6-9938-0a7333f0bb0b.png)

**Comment by ajmos** [comment]
Is this too abstract? 
![screenshot from 2017-02-19 18 45 11](https://cloud.githubusercontent.com/assets/25403432/23107967/a38f91ba-f6d3-11e6-8232-5ad8a3ee9baf.png)

**Comment by dridk** [comment]
The idea of making everything with square is a good idea.

**Comment by dridk** [comment]
Just a try ... 
![spectacle kr5276](https://cloud.githubusercontent.com/assets/1911063/23108114/971d70c0-f708-11e6-843b-f26c4ce44ddb.png)

**Comment by natir** [comment]
The usage of 4 color is very great, all bioinformaticien see one day graphe like this
![](http://www.oezratty.net/wordpress/wp-content/WindowsLiveWriter/Les-dessous-techniques-du-squenage-du-gn_82A7/DNA-sequence_thumb.gif).
In reality it's an old representation (new sequencer technology use 3 or 2 color some technology 1 or no color) but we stay use this 4 color.

The logo isn't too abstract, but the fastqt logo in my mean is for an aligner, not for quality control.

Big Thanks for your work.

**Comment by ajmos** [comment]
Thanks.
What do you mean by "fastqt logo in my mean is for an aligner , not for quality control?"
I definitely styled it to represent "alignment" and "speed.

Also, here are some little updates .

![screenshot from 2017-02-20 08 26 06](https://cloud.githubusercontent.com/assets/25403432/23126799/753bd2e2-f746-11e6-9355-3f0282e8969e.png)

**Comment by natir** [comment]
Sorry @ajmos I am not clear.
In bioinformatique we use matrice to compare/align sequence and if sequence is very similar we can see a diagonal in the matrice it's an example ![](http://acces.ens-lyon.fr/evolution/logiciels/anagene/programmes-de-1ere-s-2011/expression-de-linformation-genetique/dotplot-1/resolveUid/6ea4a0907e5acc79ba831898afccb2e5)

Whoa the update is very very good !!!!!!

**Comment by ajmos** [comment]
Oh, that's interesting. I had no idea it looks like that !

And, I did edit the update - there was another version of "Variant" that I removed because I didn't like it. ..

**Comment by natir** [comment]
I Like the variant logo because for detect a variant we need make a multiple alignment and find position where isn't match and a representation of multi-alignement look like the logo. The logo look like too a bottleneck and the many objectif of CuteVariant is filtering data.

Very very good job thanks.

**Comment by ajmos** [comment]
No problem! Let's wait a few days to see if other inspiration strikes or if I want to modify anything. If not, I'll send you the vectors of what we have now, just with everything tidied up, aligned, etc.

**Comment by dridk** [comment]
Too simple and abstract from my point of view. I would prefere some curve, gradient and shadow. 
Or maybe keep the main shape, and add an Icon background as I show before. 
So Actually, for this issue, we just need the FastQt icon. Other application are not finished, so we can wait.

**Comment by ajmos** [comment]
I never send out a logo before showing it to a few people, either in person or via email. So far, it's extremely understandable to everyone I've shown this to.

I allow the information I wish to express to define the style of the logo, not the other way around. I believe this is the correct way to design anything.Additionally, adding curves, gradients and shadows will not make it any less abstract.

**Comment by ikit** [comment]
My contribution to the reflexion. All logos done with the "chevrons", the base of the main logo. And flat color style like for office suite, one color by tool.

![labsquare logos](https://cloud.githubusercontent.com/assets/2109206/23137280/6b22b0e0-f7a1-11e6-9e46-bd66c7ffbafe.png)

**Comment by ajmos** [comment]
@ikit , Can you explain the designs you made? I also predominantly see a syringe and a faucet/tap in the CuteVariant.

**Comment by ikit** [comment]
@ajmos : sure ^^. For bigBrowser, it's like an eye, the symbolic of the eye for bigbrother have been already explained by @dridk. For FastQt, it's look like a graphic, as fastqt produce it to show the quality of the fastq file. And for CuteVariant, it's a "filter", little square are variants that are filtered to keep only variant of interest.

**Comment by Aluriak** [comment]
Just my grain of salt: the external square of BigBrowser logo should expose dna material shape. In last proposition, we have the Big Brother, but not the DNA.
Another way to put DNA shape in this logo is to draw one in the middle square.

Follows a draft (!) of my proposition.

![bigbrowser](https://cloud.githubusercontent.com/assets/1257159/23205045/cda262e0-f8e8-11e6-8da2-86d7766d9df3.png)

**Comment by pburdette** [comment]
@dridk Hey I do a lot of open source design and I'm a full time web designer. Attached you will find a few explorations. I'm digging the DNA one I cranked out this morning. Thoughts? 
![screen shot 2017-02-27 at 1 34 57 pm](https://cloud.githubusercontent.com/assets/20526900/23374321/c6654030-fcf1-11e6-91e4-ffaba84c36e7.png)

**Comment by pburdette** [comment]
Didnt realize your brand name is like this "FastQt". Attached is better example 
![screen shot 2017-02-27 at 1 39 11 pm](https://cloud.githubusercontent.com/assets/20526900/23374409/33b38e26-fcf2-11e6-9eee-c87a9c52ee75.png)

**Comment by dridk** [comment]
Thanks ! That's a good start. 
The problem is that the logo need to fit into a square (ex: I mean 64x64 size). You may try to use labsquare blue background and put one of your motif into it : 
![image](https://cloud.githubusercontent.com/assets/1911063/23374549/0ebb3ed8-fd25-11e6-822b-5b8f67bffd9c.png)

**Comment by dridk** [comment]
Yes Qt is an abreviation for "Cute". So It's FastQt . (pronnonced FastCute)

**Comment by pburdette** [comment]
hmm. Might mess with that layout but we can make it happen.

What about this @dridk 

![screen shot 2017-02-27 at 2 00 15 pm](https://cloud.githubusercontent.com/assets/20526900/23375146/4a497256-fcf5-11e6-9b7e-f7c994fec7c9.png)

**Comment by dridk** [comment]
here is a template suggestion as svg 
[labsquare-template.svg.zip](https://github.com/labsquare/fastQt/files/804821/labsquare-template.svg.zip)

![image](https://cloud.githubusercontent.com/assets/1911063/23376799/ca4fd2be-fd2d-11e6-871e-9e32e14338f3.png)

**Comment by dridk** [comment]
@beardedpayton your logo becomes better. But your dna curve doesn't respect same width. 
I think fastqt should have something with statistics. For exemple boxplot or something else. 
That's because the main goal of the app is to produce this plot : 

![image](https://cloud.githubusercontent.com/assets/1911063/23377327/f46e1db0-fd2f-11e6-83bd-76290f0792fc.png)

**Comment by dridk** [comment]
@beardedpayton You can check the website that I try to build : 
http://labsquare.org/test/landing_labsquare.html
You may want to use this texture that I like prety much : http://dridk.labsquare.org/images/splash.svg

**Comment by pburdette** [comment]
Okay I can make it happen.. @dridk

**Comment by pburdette** [comment]
@dridk 

Okay so I wouldn't use that poly fill for any type of icon or logo. They are awesome pieces for sections in sites or print material. But when you start to resize them for a logo/icon they can be way too dense on the eyes. A little too much if you ask me. 

That being said, we want this icon/logo to be simple and clean correct? We want it to work from 64x64px and up?

How do you feel about this (I like this direction the best so far)

![screen shot 2017-02-27 at 4 07 29 pm](https://cloud.githubusercontent.com/assets/20526900/23379945/e2bf87b2-fd06-11e6-9984-f3421f7ece4c.png)

**Comment by ajmos** [comment]
Why are there 7 bars specifically?

**Comment by pburdette** [comment]
@ajmos no reason tied to the brand. The box plot can have tons, 7 felt right for the icon. Needed more than 3-5 bars to show we are talking some sort of statistics here.

**Comment by ajmos** [comment]
This is what your logo looks like as a shortcut in a taskbar
![screenshot from 2017-02-27 16 19 14](https://cloud.githubusercontent.com/assets/25403432/23380391/9e308e32-fd08-11e6-94fa-242f60162dae.png)

**Comment by dridk** [comment]
@beardedpayton I like this one ! The motif is simple and good ! 
Maybe remove serif in font. 
For the background template, I would like some shadow as I suggest. Could you try to use mine template, and propose different color ?

**Comment by dridk** [comment]
@ajmos maybe by removing some bare and make them bigger ?

**Comment by pburdette** [comment]
@ajmos thats becuase it's not designed at 64px x 64px yet. Thats at 800px x 600px. I'm getting feedback not shipping a final product yet.

**Comment by pburdette** [comment]
@ajmos and you just used a screenshot of trying to test my logo. Not a vector export from illustrator. SO of course it would do that lol

**Comment by pburdette** [comment]
@dridk okay sounds good on the font. I can explore some better suited sans-serif. 

We can add the shadow on the logo in illustrator or you can do it with CSS in the browser. What do you prefer ?

And if you were wondering what @ajmos was talking about. He is trying t test a screenshot not the actual logo lol

**Comment by ajmos** [comment]
here's the vector , made slightly larger than the screenshot of the raster
![screenshot from 2017-02-27 16 29 08](https://cloud.githubusercontent.com/assets/25403432/23380747/fad0575c-fd09-11e6-9f9a-f1617eda765a.png)

**Comment by pburdette** [comment]
@ajmos I don't think you understand what you are doing. You are grabbing a screenshot off my desktop from my snipping tool. There is no way you would have access to a vector.

**Comment by ajmos** [comment]
![screenshot from 2017-02-27 16 32 45](https://cloud.githubusercontent.com/assets/25403432/23380852/630f1baa-fd0a-11e6-9991-8b8d83f53c46.png)

**Comment by dridk** [comment]
@beardedpayton generally, I have a complete svg with all feature. So I can easily change if it's necessary

**Comment by pburdette** [comment]
@dridk give me a moment and I will attach what you need here with the shadow and futura bold font.

**Comment by dridk** [comment]
Get inspired by this icon for the template layout, which give it more relief with shadow and light
![image](https://cloud.githubusercontent.com/assets/1911063/23381108/8c703230-fd3d-11e6-8d59-09bf65c68bd3.png)

**Comment by dridk** [comment]
Maybe using same color and light with your motif ? Just some suggestion.. I change my mind every time. 

svg icon is avaible there : https://github.com/cgaebel/gluon/blob/bd3e2cd96d3a7af66d4114f88705458a9a623ae3/creator/icons/gluon-creator-256.svg

**Comment by pburdette** [comment]
@dridk I'll provide you with app icon and one you can use on the web. The app icon is at 64x64.. Designed exactly for that (when you get that small, you have to design icons around that).

Probably sometime this week. So contact me if you have any questions about current direction.

**Comment by dridk** [comment]
ok thanks! Let's see ! If you can provide vectorial data, it would be greate too.

**Comment by pburdette** [comment]
@dridk what's your email? How would you like to receive the finished files?

**Comment by dridk** [comment]
You can join a zip file attached to this conversion . Or upload it using https://transfer.sh/( OR https://framadrop.org/)  and paste the link here.

**Comment by pburdette** [comment]
@dridk zip file is attached. You will find a 64x64 version of the icon, web version, svg and illustrator file

[FastQt.zip](https://github.com/labsquare/fastQt/files/807159/FastQt.zip)

**Comment by dridk** [comment]
@beardedpayton Thanks you very much. So, it's not perfect but it's better than the actual one. 
I will try to make some improvement. Shadow, border and color adjustement. And propose to the team.

@ajmos No offense, But  I can  reproduce all your design in less than 5 min too.  ( @ajmos and @beardedpayton too). You are only using primitive shape, without curves, light or shadow. Probably because you are following the trending of flat design, which is a bad things from my point of view.  
I was working with a Professional designer from Linux/KDE. And logo was really good. 
I suggest you to get inspired by the designer [Nuno_Pinheiro ](https://en.wikipedia.org/wiki/Nuno_Pinheiro_(artist)) and see what he did : http://pinheiro-kde.blogspot.fr/

Well, this is an opensource project. So I would like to thanks both of you for your help and the time you give us.

**Comment by pburdette** [comment]
@dridk @ajmos 

Flat design isn't a bad thing. It's based on your taste for your brand. Some of the worlds most successful logos are simple, clean and flat. A logo could take 10 mins once you find the right variation, but it probably could take 2 weeks to get to that point.

When it's all said and done it's what works best for your project or brand. It could be made in paint, but if it's successful it works. 

Being able to reproduce a design in 5 minutes means nothing. Take Nike for example, I can reproduce their logo and many others in 5 minutes or less. But how iconic is that to their brand? It's huge. It's about the process, coming up with a logo that works for your brand. Not how quick it is to make it. Designers go through tons of variations on an AI art board until something feels right. 

Keep that in mind.

**Comment by dridk** [comment]
@beardedpayton I was just aswering @ajmos who said he can do your logo in few minutes too. I removed the post because he published a huge picture inside. 
I agree with you. I just make a distinction between a "logo" and an "application icon". 
For exemple Dropbox "logo" is a the simple box in a flat design. 
An "application icon" can be something like this .  http://nantesstnazaire.cci.fr/sites/default/files/mediatheque/po/dropbox.png

**Comment by ajmos** [comment]
@dridk  Way to get in the middle of a convo @beardedpayton  and I were having. The "I did it in a minute" was purely to communicate that I actually made the vector in the short time between messages we were exchanging. I wasn't saying "look at how simple your logo is, dude".

I removed all my posts and work above. I like the concept I made, and I'll keep it in case I need to adapt it for a similar project or company. You definitely don't have my permission to use any of it.

**Comment by dridk** [comment]
@ajmos ok, so I am  sorry for that! I misunderstood it. ( my bad english probably).

**Comment by dridk** [comment]
So, I will close this issue this week except if somebody from the team disagree or if there is another suggestion. 
Then we will use @beardedpayton icon and give him the bounty.

**Comment by ajmos** [comment]
@dridk Ca va, mais je croix que ce que tu voulais c''etait quelqu'un pour executer ton propre idee. Tu devais franchement clarifier ca au tout debut.

**Comment by pburdette** [comment]
@dridk Sounds good! Let me know if you have any questions or if I can help with anything.

**Comment by dridk** [comment]
@beardedpayton you didn't ask for the prime. 
https://www.bountysource.com/issues/42015876-application-icon

**Comment by Erioldoesdesign** [comment]
Can I close the associated open source design job request with this please? https://opensourcedesign.net/jobs/jobs/2017-02-17-graphic-designer-for-genomics-application-logo

**Comment by dridk** [comment]
yes
