### ISSUE TITLE
Bug durring make install

### ISSUE THREAD

**Issue by natir** [labsquare/fastQt#37]
Hi,

@JuneBS report to a problem durring the install phase of make.

Version : devel branch
Distributon : Manjaro
Error message : 
```
sudo make install
 install -m 755 -p fastqt /usr/local/bin/fastqt 
strip /usr/local/bin/fastqt 
install -m 755 -p /media/DATA/Projects/fastQt/fastqt.desktop /usr/share/applications/
strip /usr/share/applications/fastqt.desktop 
strip:/usr/share/applications/fastqt.desktop: Format de fichier non reconnu
make: [Makefile:1141: install_desktop] Error 1 (ignorée)
install -m 755 -p /media/DATA/Projects/fastQt/fastqt.png /usr/share/icons/hicolor/48x48/apps/
strip /usr/share/icons/hicolor/48x48/apps/fastqt.png 
strip:/usr/share/icons/hicolor/48x48/apps/fastqt.png: Format de fichier non reconnu
make: [Makefile:1151: install_icons] Error 1 (ignorée)
```

I didn't repoduce this bug on Fedora 25

**Comment by natir** [comment]
Potential solution : 

- Replace the strip command by echo and add a custom target https://lists.gt.net/mythtv/dev/141885
- I didn't fully understand this https://forum.qt.io/topic/39263/resolved-installs-add-strip-command-to-makefile/2
- But desktop and icon aren't executable in my repo https://stackoverflow.com/questions/16275838/cant-install-a-image-file-anymore-whats-wrong

@JuneBS can you check the permission of fastqt.desktop and fastqt.png

**Comment by Jnsll** [comment]
For both of them, i've got 'rwxrwxrwx' and root:root for user/group.

**Comment by natir** [comment]
In the repo or in the install path ?

If file is executable in repo execute ```chmod -x``` on file solve the issue.

**Comment by Jnsll** [comment]
In the repo. I did `chmod -x fastqt.png` and `chmod -x fastqt.desktop`. But nothing changed. Still the same error.

**Comment by natir** [comment]
the user and the group is root ?

If it's true change to your basic user.

**Comment by Jnsll** [comment]
Is that normal that i cannot change the user and group of those files...? Still root:root ...
(`sudo chown jnsll fastqt.desktop` and `sudo chown jnsll fastqt.png`)

**Comment by natir** [comment]
You clone the repo with the root user ?

try : 
```
sudo chown jnsll::jnsll fastqt.desktop
sudo chown jnsll::jnsll fastqt.png
```

**Comment by Jnsll** [comment]
No, i cloned it with the basic user. (I redid it to confirm.)
And when doing the command `sudo chown jnsll::jnsll fastqt.desktop`, i get:
`chown: groupe incorrect: « jnsll::jnsll »`

**Comment by natir** [comment]
Sorry remove one ```:``` in command.

**Comment by Jnsll** [comment]
My bad. 
Well, the user and group don't change nevertheless... Still root:root.

**Comment by natir** [comment]
Ok it's very very strange.

**Comment by Jnsll** [comment]
I'll start from scratch again after rebooting (cloning, etc).

**Comment by Jnsll** [comment]
After rebooting and cloning the project again, I still have the error and i cannot change the user and group of the files..

**Comment by natir** [comment]
Did you check the permission before run make install  ?
The other file in your repo have the same owner and permission ?
Did you run ```make``` before run ```sudo make install``` ?

Thanks

**Comment by Jnsll** [comment]
After cloning, the permissions are already full (`rwxrwxrwx`) and root is the user/group for the files.
Here is a screenshot of the files just after cloning the project (no `qmake` nor `make` etc). 
![after_cloning](https://cloud.githubusercontent.com/assets/15047775/23157836/0334d022-f81d-11e6-9824-6ff748094e8e.png)
I did run `make` before `sudo make install`.

**Comment by dridk** [comment]
did you use "sudo" for cloning ? sudo git ? 
you miss -R to change folder rights . .    ```sudo chown -R name:name path/``` 
I think your system settings has something wrong

**Comment by Jnsll** [comment]
Well, i've searched a little and I think i may know the problem. You're right, the system settings are kind of the issue. I've cloned the project on a ntfs partition so using root as default for the user and group. That may cause the issue. I will try cloning the project on another partition (and not a ntfs one).

**Comment by natir** [comment]
Ok if you clone the repo one a ntfs partition is normal.

All trouble come from the options used for mount this partition.
