### ISSUE TITLE
Avoid decompression twice 

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#38]
Quote from @Arkanosis :
I'll rewrite this to avoid decompressing files twice (I'm pretty sure more time is spent currently decompressing compared to actually computing the statistics). Feel free to clean up, though, as I'm not sure when I'll do this.

**Comment by dridk** [comment]
For gzip, the total uncompress size is avaible from the 4 last bytes of the compressed file. 
Nothing for bgzip... maybe something for LZMA

**Comment by Arkanosis** [comment]
Awesome! \o/

**Comment by dridk** [comment]
yes ! it was really easy ! It's now incredible fast !

**Comment by ikit** [comment]
nice trick ! good to know.
