### ISSUE TITLE
Don't use extension to choose the compression format and check if file contains fastq data

### ISSUE THREAD

**Issue by natir** [labsquare/fastQt#52]
Actualy we use the last extension in filename to choose the compression format, we can replace it by read the magic number.

- gz : 1f 8b (2 bytes)
- bz2 : 'BZ' (16 bytes)
- xz : { 0xFD, '7', 'z', 'X', 'Z', 0x00 } (6 bytes)

For check if file is fastq just read the first character of first 4 lines -> @, [a-Z], +, [.]

**Comment by dridk** [comment]
This issue is related to #51  too. Could you manage this one too ?

**Comment by dridk** [comment]
Fixed Crash when you open xz file : 3d0cf565aa3b6b1bbed22fe8ae38492a5d6c60d8
Need to release a 0.2.2 version
