### ISSUE TITLE
Open files other than with .fastq extension

### ISSUE THREAD

**Issue by A-N-Other** [labsquare/fastQt#53]
Users don't necessarily have a .fastq<.gz/etc> extension on their FASTQ files - .fq / .fq.gz / .trim / etc are also common - users should be able to choose what to load in.  This might be OK as a default, but at least there should be an option to display 'All files' in the file browser when loading files for analysis.  This also impacts the drag-and-drop functionality.

**Comment by natir** [comment]
Thank for this issue. We plan to stop use the extension of file to detect their format in 0.3, see issue #52.

**Comment by natir** [comment]
@A-N-Other Actual devel branch (commit c32225bd1b8b38ac608d673e4ac8e3cb4a862a88) support more and any extension file.

Thanks for your interest for this project.

**Comment by natir** [comment]
You can use https://transfer.sh/yaTa9/fastqt-git.c32225b-x86-64.appimage (link is available just for 14 days).
