### ISSUE TITLE
Format Total Sequence print in Basic stat analysis

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#55]
in Basic Stat Analyis, 
Total Sequences fields is not easy readable for big number. 
Could you print : 4 000 000 instead 4000000

**Comment by natir** [comment]
Maybe you could be find some solution in https://doc.qt.io/qt-5/qvalueaxis.html#applyNiceNumbers

**Comment by dridk** [comment]
this is a request for the basicStatAnalysis. It's a simple table . 
Si the goal is just to convert a QString ("10000000") to QString("100 000 000 ") . Qt may provide some magic for that.
