### ISSUE TITLE
Generated image isn't a valid png

### ISSUE THREAD

**Issue by natir** [labsquare/fastQt#56]
Version : devel (c32225bd1b8b38ac608d673e4ac8e3cb4a862a88)

Step to reproduce : 

- Run fastQt
- Analysis file
- Save all data generate by analysis in directory
- Try to open any png with eog (eye of gnome default image viewer of gnome project)

**Comment by dridk** [comment]
I don't have eog. But I can open it with other image viewer. 
Same bug using firefox or other viewer ?

**Comment by natir** [comment]
I find where is the trouble image, the content of *.png file isn't a png file but is svg. eog use the extension to detect the file type, other image viewer maybe read the begin of file.

**Comment by natir** [comment]
Commit solve : 2270778afd29f6791a31a9c2a75abfd2b0e1ded8
