### ISSUE TITLE
Create Per Base N Content

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#6]
Create Per Base N Content according FastQC Module 

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/6%20Per%20Base%20N%20Content.html

**Comment by natir** [comment]
Closed by a8b41628c05157edbdd70f821f3fe53f3d592ef2

**Comment by dridk** [comment]
I think you just miss one line . Not sure, But FastQt and FastQC plot are note same. I should have no N... ( if FastQC is the gold standard)


![ttt](https://cloud.githubusercontent.com/assets/1911063/21901768/56b85c8e-d8f9-11e6-8231-e08f0fec4e61.png)

  That's probably because you miss the following conditions .  
         for (int i=0; i<sequence.size(); ++i)
         if (sequence.sequence().at(i) == 'N') // this one ? 
         ++(*counts[static_cast<int>(sequence.sequence().at(i))])[i];

**Comment by natir** [comment]
I think the trouble is in the Y axis generation 100 % isn't realy 100 % but just max of Series, if you reuse 

```c++
chart->createDefaultAxes();
```

For generate Y axis you see the value is very low.

**Comment by natir** [comment]
Solve by 4e3f2ffc87dfd2f2f908ec6cfb7f9eec73b38505
