### ISSUE TITLE
Create Per sequence GC Content

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#7]
Create per Sequence GC content according FASTQC Module 

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/5%20Per%20Sequence%20GC%20Content.html

**Comment by natir** [comment]
Partially close by af9157f800643931595f6b7866410c30a3a522b9

Normal distribution isn't add on graph

**Comment by dridk** [comment]
Good job!!! 
for normal distribution, I guess you may use this : http://en.cppreference.com/w/cpp/numeric/random/normal_distribution

**Comment by natir** [comment]
Theoretical distribution isn't very important feature, but if you want it, you can see issue #13.

**Comment by dridk** [comment]
@natir Could you set Y Axis in reads count not in percent ? 
Like FastQC does , as you can see here : 
![image](https://cloud.githubusercontent.com/assets/1911063/21923205/0497c910-d973-11e6-9cd7-4e91186b86c2.png)

**Comment by natir** [comment]
Solve by 0a53c22bf470281d136d6e22a2a1a9fe99d3d845
