### ISSUE TITLE
How to cite fastqt 

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#71]
Is it okay ? Or would you like all name ? 
Labsquare  (2017). FastQt: a quality control tool for high throughput sequence data. Available online at: https://github.com/labsquare/fastQt

Sacha schutz, Pierre Marijon, Jeremy, etc ...  (2017). FastQt: a quality control tool for high throughput sequence data. Available online at: https://github.com/labsquare/fastQt

**Comment by natir** [comment]
Labsquare Team, et al (2017). FastQt: a quality control tool for high throughput sequence data. Available online at: https://github.com/labsquare/fastQt ?
