### ISSUE TITLE
sequence length distribution out of range

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#84]
My reads distribution is : 0 - 126 bp. 
But, "the sequence length distribution" graph display x axis range to 128 for the maximum.

**Comment by Arkanosis** [comment]
I see no explicit call to `setMax()` on the X axis. Might be the reason why…

BTW, it seems the line 143 (`if (mGraphCounts[i] > mMax) mMax = mGraphCounts[i];`) serves no purpose since the value is unconditionally overwritten at line 148 (`mMax = maxLen;`).
