### ISSUE TITLE
X Scale is wrong for PerBaseAnalysis and PerBaseNAalysis

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#85]
![image](https://user-images.githubusercontent.com/1911063/28123012-2b7741c4-6720-11e7-85fa-9c20ea6827c5.png)

**Comment by natir** [comment]
Please send the file I have no trouble on my test file.

**Comment by dridk** [comment]
https://framadrop.org/r/8gxaml5uRD#IF+GhWG995zbEgUA5MSzVoveIe5r+qdCJQLeOVaXG/8=
