### ISSUE TITLE
Pb with .gz files size

### ISSUE THREAD

**Issue by VictorYt** [labsquare/fastQt#88]
![file_size](https://user-images.githubusercontent.com/11853750/28370487-ae74dd0a-6c9a-11e7-968f-d658b069800a.png)

All my fastq.gz files are around 4 and 6 GB ... normaly

**Comment by natir** [comment]
Can you send an example file ? maybe you can use https://framadrop.org/ and send the link to me by e-mail, if it's sensible data.
