### ISSUE TITLE
Arch Installer Broken

### ISSUE THREAD

**Issue by rnbwdsh** [labsquare/fastQt#95]
TL;DR: GOTO PKGBUILD, replace 1a66ec8211ea07755deed996dbeda6c04c595c61b77d7e6caf913442b9a637bf with 58b20dd5ece5aaf040ec8435de913170614e2a3217feeb6a00bc17f3eca87af0 and "fastQt-" with "FastQt-"

Long version:
Multiple errors in PKGBUILD
The sha256 is broken (should be 58b20dd5ece5aaf040ec8435de913170614e2a3217feeb6a00bc17f3eca87af0) and the package trys to cd into fastQt... but you should cd into FastQt (uppercase... linux cares) After that, it works fine for me. 

(duplicate from the AUR page, https://aur.archlinux.org/packages/fastqt)

**Comment by natir** [comment]
@StuntsPT you have the power to solve this issue :)

**Comment by StuntsPT** [comment]
Fixed.
Sorry I don't really know what the issue could be. I could have sworn it was working... FastQt is installed in all my work machines via PKGBUILD.
Anyway, all is working now. Thank you for the heads up.
